[window]
decorations = "None"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

live_config_reload = "true"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "default"]

[font]
size = 17
